development:
  adapter: mysql
  encoding: utf8
  database: sat_dev
  username: root
  password: 

test:
  adapter: mysql
  encoding: utf8
  database: sat_test
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  database: sat_prod
  username: root
  password: 
